apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  namespace: weather-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-container
          image: diegobsc/weather-app:latest
          ports:
            - containerPort: 8080
