apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: weather-space
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
